# Test your FastAPI endpoints

GET http://127.0.0.1:6002/
Accept: application/json

###

GET http://127.0.0.1:6002/hello/User
Accept: application/json

###

GET http://127.0.0.1:6002/play/scissors
Accept: application/json

###