apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.app-sync-succeed.slack: 02-memo-care-deployment
    notifications.argoproj.io/subscribe.app-sync-failed.slack: 02-memo-care-deployment
spec:
  project: default
  source:
    repoURL: 'https://github.com/huinno-yoseph/rock-paper-scissors.git'  # YAML 파일들이 있는 Git 리포지토리
    targetRevision: HEAD  # 배포할 Git 브랜치
    path: k8s  # Kubernetes manifest 파일이 위치한 디렉토리
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: care
  syncPolicy:
    automated:
      prune: true
      selfHeal: true